### ISSUE TITLE
Rider: ArrayIndexOutOfBoundsException: 8 >= 4

### ISSUE THREAD

**Issue by anton-arsentyev** [NLSurfMan/tasks#32]
Have such exception in Rider 2017.3.1

Steps:

1. Add task
2. Remove task

```
java.lang.ArrayIndexOutOfBoundsException: 8 >= 4
			at java.util.Vector.elementAt(Vector.java:474)
			at javax.swing.tree.DefaultMutableTreeNode.getChildAt(DefaultMutableTreeNode.java:245)
			at javax.swing.tree.VariableHeightLayoutCache.treeNodesRemoved(VariableHeightLayoutCache.java:562)
			at javax.swing.plaf.basic.BasicTreeUI$Handler.treeNodesRemoved(BasicTreeUI.java:3903)
			at org.dubik.tasks.ui.tree.TaskTreeModel.fireTreeNodesRemoved(TaskTreeModel.java:264)
			at org.dubik.tasks.ui.tree.TaskTreeModel.handleDeleteTaskEvent(TaskTreeModel.java:176)
			at org.dubik.tasks.model.impl.TaskModel.fireDeleteTaskEvent(TaskModel.java:318)
			at org.dubik.tasks.model.impl.TaskModel.deleteTask(TaskModel.java:148)
			at org.dubik.tasks.TaskController.deleteTask(TaskController.java:213)
			at org.dubik.tasks.ui.actions.RemoveTaskAction.deleteTasks(RemoveTaskAction.java:72)
			at org.dubik.tasks.ui.actions.RemoveTaskAction.actionPerformed(RemoveTaskAction.java:65)
```

**Comment by NLSurfMan** [comment]
Thanks for the steps. I'll look into it.
